// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProductByIDRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductByIDRequest) Reset()         { *m = GetProductByIDRequest{} }
func (m *GetProductByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductByIDRequest) ProtoMessage()    {}
func (*GetProductByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *GetProductByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductByIDRequest.Unmarshal(m, b)
}
func (m *GetProductByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetProductByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductByIDRequest.Merge(m, src)
}
func (m *GetProductByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductByIDRequest.Size(m)
}
func (m *GetProductByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductByIDRequest proto.InternalMessageInfo

func (m *GetProductByIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type Product struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                string               `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Currency             string               `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Product) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Product) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Product) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProductByIDRequest)(nil), "boldapi.pre.GetProductByIDRequest")
	proto.RegisterType((*GetProductResponse)(nil), "boldapi.pre.GetProductResponse")
	proto.RegisterType((*Product)(nil), "boldapi.pre.Product")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0x9a, 0xef, 0xeb, 0xd7, 0x2d, 0x5f, 0x0f, 0x6b, 0x84, 0x10, 0x84, 0x96, 0x5c,
	0xec, 0xc5, 0x0d, 0xd4, 0x07, 0x90, 0x96, 0x82, 0x78, 0x93, 0xe8, 0xc9, 0x8b, 0x6c, 0x92, 0x31,
	0x2e, 0x34, 0xd9, 0xed, 0xee, 0x46, 0x28, 0xe2, 0x45, 0x5f, 0x40, 0xf0, 0xd1, 0x7c, 0x00, 0x11,
	0x7c, 0x10, 0xe9, 0x66, 0x63, 0xad, 0x28, 0x78, 0xdb, 0xff, 0xcc, 0x6f, 0x26, 0x33, 0xff, 0x09,
	0xfa, 0xaf, 0x40, 0xde, 0xb0, 0x0c, 0x88, 0x90, 0x5c, 0x73, 0xdc, 0x4f, 0xf9, 0x22, 0xa7, 0x82,
	0x11, 0x21, 0x21, 0xdc, 0x2b, 0x38, 0x2f, 0x16, 0x10, 0x53, 0xc1, 0x62, 0x5a, 0x55, 0x5c, 0x53,
	0xcd, 0x78, 0xa5, 0x1a, 0x34, 0x1c, 0xda, 0xac, 0x51, 0x69, 0x7d, 0x15, 0x6b, 0x56, 0x82, 0xd2,
	0xb4, 0x14, 0x16, 0x38, 0x28, 0x98, 0xbe, 0xae, 0x53, 0x92, 0xf1, 0x32, 0x2e, 0x78, 0xc1, 0x37,
	0xe4, 0x5a, 0x19, 0x61, 0x5e, 0x0d, 0x1e, 0xed, 0xa3, 0xdd, 0x63, 0xd0, 0xa7, 0x92, 0xe7, 0x75,
	0xa6, 0x67, 0xab, 0x93, 0x79, 0x02, 0xcb, 0x1a, 0x94, 0xc6, 0x03, 0xe4, 0xb2, 0x3c, 0x70, 0x46,
	0xce, 0xb8, 0x93, 0xb8, 0x2c, 0x8f, 0xe6, 0x08, 0x6f, 0xc0, 0x04, 0x94, 0xe0, 0x95, 0x02, 0x4c,
	0x50, 0x57, 0x34, 0x21, 0x83, 0xf6, 0x27, 0x3e, 0xf9, 0xb4, 0x0b, 0x69, 0xf1, 0x16, 0x8a, 0x5e,
	0x1d, 0xd4, 0xb5, 0xc1, 0xaf, 0x5f, 0xc0, 0x18, 0x79, 0x15, 0x2d, 0x21, 0x70, 0x47, 0xce, 0xb8,
	0x97, 0x98, 0x37, 0xf6, 0xd1, 0x1f, 0x21, 0x59, 0x06, 0x41, 0xc7, 0x04, 0x1b, 0x81, 0x43, 0xf4,
	0x2f, 0xab, 0xa5, 0x84, 0x2a, 0x5b, 0x05, 0x9e, 0x49, 0x7c, 0x68, 0x7c, 0x84, 0x50, 0x26, 0x81,
	0x6a, 0xc8, 0x2f, 0xa9, 0x0e, 0x76, 0xcc, 0x50, 0x21, 0x69, 0x5c, 0x23, 0xad, 0x17, 0xe4, 0xbc,
	0x75, 0x6d, 0xe6, 0x3d, 0xbe, 0x0c, 0x9d, 0xa4, 0x67, 0x6b, 0xa6, 0x7a, 0xdd, 0xa0, 0x16, 0x79,
	0xdb, 0xc0, 0xff, 0x6d, 0x03, 0x5b, 0x33, 0xd5, 0x93, 0x07, 0x07, 0x0d, 0xec, 0x8e, 0x67, 0xcd,
	0x99, 0xf1, 0x12, 0x0d, 0xb6, 0x5d, 0xc6, 0xd1, 0x96, 0x4f, 0xdf, 0x9e, 0x20, 0x1c, 0xfe, 0xc0,
	0xb4, 0xee, 0x47, 0xe1, 0xfd, 0xf3, 0xdb, 0x93, 0xeb, 0x63, 0x6c, 0x7e, 0x16, 0xeb, 0xb1, 0x8a,
	0x6f, 0x59, 0x7e, 0x37, 0xf3, 0x2e, 0x5c, 0x91, 0xa6, 0x7f, 0xcd, 0xc0, 0x87, 0xef, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x15, 0xb7, 0x29, 0x34, 0x71, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProductByID(ctx context.Context, in *GetProductByIDRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, "/boldapi.pre.ProductService/GetProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	GetProductByID(context.Context, *GetProductByIDRequest) (*GetProductResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) GetProductByID(ctx context.Context, req *GetProductByIDRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductByID not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boldapi.pre.ProductService/GetProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductByID(ctx, req.(*GetProductByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "boldapi.pre.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductByID",
			Handler:    _ProductService_GetProductByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
